import React, { useState, useEffect } from 'react';
import {
    MdAccountTree,
    MdAdd,
    MdSearch,
    MdAutoGraph,
    MdFileUpload,
    MdFileDownload,
    MdDelete,
    MdEdit,
    MdArrowBack,
    MdDashboard,
    MdLightbulb,
    MdCheckCircle,
    MdFolder,
    MdCategory,
    MdSchedule
} from 'react-icons/md';
import { flowchartService } from '../services/api';
import { FLOWCHART_TEMPLATES } from '../constants/FlowchartTemplates';
import FlowchartCanvas from '../components/FlowchartCanvas';
import AutoFlowchartGenerator from '../components/AutoFlowchartGenerator';
import Modal from '../components/Modal';
import { toast } from 'react-toastify';
import { useAuth } from '../context/AuthContext';

const Flowcharts = () => {
    const { hasAccess } = useAuth();
    const [flowcharts, setFlowcharts] = useState([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');
    const [statusFilter, setStatusFilter] = useState('All');

    // Selected active flowchart for canvas editing
    const [activeFlowchart, setActiveFlowchart] = useState(null);

    // Modals state
    const [showNewModal, setShowNewModal] = useState(false);
    const [showAutoGenerator, setShowAutoGenerator] = useState(false);
    const [showTemplatesModal, setShowTemplatesModal] = useState(false);
    const [showImportModal, setShowImportModal] = useState(false);

    // Form State for creating flowchart
    const [formData, setFormData] = useState({
        title: '',
        description: '',
        category: 'General',
        rawSteps: ''
    });

    const [importJsonText, setImportJsonText] = useState('');

    const fetchFlowcharts = async () => {
        setLoading(true);
        try {
            const res = await flowchartService.getAll({
                status: statusFilter === 'All' ? undefined : statusFilter,
                search: search ? search.trim() : undefined
            });
            if (res.data && res.data.data) {
                setFlowcharts(res.data.data);
            }
        } catch (error) {
            console.error('Failed to fetch flowcharts:', error);
            toast.error('Failed to load flowcharts');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchFlowcharts();
    }, [statusFilter, search]);

    const handleCreateNew = async (e) => {
        e?.preventDefault();
        if (!formData.title.trim()) {
            toast.error('Please provide a title');
            return;
        }

        try {
            const res = await flowchartService.create(formData);
            if (res.data && res.data.data) {
                toast.success('Flowchart created!');
                setShowNewModal(false);
                setFormData({ title: '', description: '', category: 'General', rawSteps: '' });
                setActiveFlowchart(res.data.data);
                fetchFlowcharts();
            }
        } catch (err) {
            toast.error(err.response?.data?.message || 'Failed to create flowchart');
        }
    };

    const handleSelectTemplate = async (tmpl) => {
        try {
            const res = await flowchartService.create({
                title: tmpl.title,
                description: tmpl.description,
                category: tmpl.category,
                rawSteps: tmpl.rawSteps,
                nodes: tmpl.nodes,
                edges: tmpl.edges,
                status: 'Draft'
            });
            if (res.data && res.data.data) {
                toast.success(`Created flowchart from "${tmpl.title}" template!`);
                setShowTemplatesModal(false);
                setActiveFlowchart(res.data.data);
                fetchFlowcharts();
            }
        } catch (err) {
            toast.error(err.response?.data?.message || 'Failed to load template');
        }
    };

    const handleAutoGenerated = async ({ nodes, edges, rawSteps }) => {
        try {
            const res = await flowchartService.create({
                title: formData.title.trim() || 'Auto-Generated Flowchart',
                description: 'Generated automatically from text steps',
                category: 'General',
                rawSteps,
                nodes,
                edges,
                status: 'Draft'
            });
            if (res.data && res.data.data) {
                toast.success('Auto-generated flowchart saved!');
                setShowAutoGenerator(false);
                setActiveFlowchart(res.data.data);
                fetchFlowcharts();
            }
        } catch (err) {
            toast.error('Failed to save auto-generated flowchart');
        }
    };

    const handleImportJSON = async () => {
        if (!importJsonText.trim()) {
            toast.error('Paste JSON payload first');
            return;
        }
        try {
            const parsed = JSON.parse(importJsonText);
            const res = await flowchartService.importJson(parsed);
            if (res.data && res.data.data) {
                toast.success('Flowchart JSON imported successfully!');
                setShowImportModal(false);
                setImportJsonText('');
                setActiveFlowchart(res.data.data);
                fetchFlowcharts();
            }
        } catch (err) {
            toast.error('Invalid JSON file format');
        }
    };

    const handleSaveCanvas = async (data) => {
        if (!activeFlowchart?._id) return;
        try {
            const res = await flowchartService.update(activeFlowchart._id, data);
            if (res.data && res.data.data) {
                setActiveFlowchart(res.data.data);
                fetchFlowcharts();
            }
        } catch (err) {
            toast.error('Failed to save changes');
        }
    };

    const handleDeleteFlowchart = async (id, e) => {
        e?.stopPropagation();
        if (!window.confirm('Are you sure you want to delete this flowchart?')) return;
        try {
            await flowchartService.delete(id);
            toast.success('Flowchart deleted');
            if (activeFlowchart?._id === id) setActiveFlowchart(null);
            fetchFlowcharts();
        } catch (err) {
            toast.error('Deletion failed');
        }
    };

    // Render Canvas Mode if active flowchart selected
    if (activeFlowchart) {
        return (
            <div className="space-y-4 animate-in fade-in duration-200">
                <div className="flex items-center justify-between">
                    <button
                        onClick={() => {
                            setActiveFlowchart(null);
                            fetchFlowcharts();
                        }}
                        className="px-4 py-2 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 font-extrabold text-xs hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors flex items-center gap-2"
                    >
                        <MdArrowBack size={18} /> Back to Flowcharts Workspace
                    </button>

                    <div className="flex items-center gap-2">
                        <span className="text-xs font-bold text-slate-500">Status:</span>
                        <select
                            value={activeFlowchart.status || 'Draft'}
                            onChange={async (e) => {
                                const newStatus = e.target.value;
                                try {
                                    await flowchartService.update(activeFlowchart._id, { status: newStatus });
                                    setActiveFlowchart(prev => ({ ...prev, status: newStatus }));
                                    toast.success(`Status updated to ${newStatus}`);
                                } catch (err) {
                                    toast.error('Failed to update status');
                                }
                            }}
                            className="px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 text-xs font-bold text-slate-800 dark:text-slate-200"
                        >
                            <option value="Draft">Draft</option>
                            <option value="Published">Published</option>
                            <option value="Archived">Archived</option>
                        </select>
                    </div>
                </div>

                <FlowchartCanvas
                    flowchartData={activeFlowchart}
                    onSave={handleSaveCanvas}
                    onAutoSave={handleSaveCanvas}
                />
            </div>
        );
    }

    return (
        <div className="space-y-8 animate-in fade-in duration-200">
            {/* Page Header */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-xl">
                <div className="flex items-center gap-4">
                    <div className="w-14 h-14 rounded-2xl bg-primary-600 text-white flex items-center justify-center shadow-lg shadow-primary-600/30">
                        <MdAccountTree size={30} />
                    </div>
                    <div>
                        <h1 className="text-2xl font-black text-slate-900 dark:text-slate-100 leading-tight">
                            Process Flowchart Builder
                        </h1>
                        <p className="text-xs font-semibold text-slate-500 mt-1">
                            Document, auto-generate, edit, and version control visual business workflows.
                        </p>
                    </div>
                </div>

                <div className="flex flex-wrap items-center gap-3">
                    <button
                        onClick={() => setShowTemplatesModal(true)}
                        className="px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 font-extrabold text-xs hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors flex items-center gap-2"
                    >
                        <MdLightbulb className="text-amber-500" size={18} /> Templates
                    </button>
                    <button
                        onClick={() => setShowAutoGenerator(true)}
                        className="px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 font-extrabold text-xs hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors flex items-center gap-2"
                    >
                        <MdAutoGraph className="text-primary-500" size={18} /> Auto-Generate
                    </button>
                    <button
                        onClick={() => setShowImportModal(true)}
                        className="px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 font-extrabold text-xs hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors flex items-center gap-2"
                    >
                        <MdFileUpload size={18} /> Import JSON
                    </button>
                    <button
                        onClick={() => setShowNewModal(true)}
                        className="px-5 py-2.5 rounded-xl bg-primary-600 hover:bg-primary-700 text-white font-extrabold text-xs shadow-lg shadow-primary-600/20 transition-all flex items-center gap-2"
                    >
                        <MdAdd size={20} /> Create Flowchart
                    </button>
                </div>
            </div>

            {/* Filter & Search Bar */}
            <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
                <div className="flex items-center gap-2 bg-slate-200/60 dark:bg-slate-800/60 p-1 rounded-2xl w-full sm:w-auto">
                    {['All', 'Draft', 'Published', 'Archived'].map(st => (
                        <button
                            key={st}
                            onClick={() => setStatusFilter(st)}
                            className={`px-4 py-1.5 rounded-xl text-xs font-black transition-all ${statusFilter === st ? 'bg-white dark:bg-slate-900 text-primary-600 dark:text-primary-400 shadow-md' : 'text-slate-600 dark:text-slate-400 hover:text-slate-900'}`}
                        >
                            {st}
                        </button>
                    ))}
                </div>

                <div className="relative w-full sm:w-72">
                    <MdSearch className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                    <input
                        type="text"
                        placeholder="Search flowcharts..."
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className="w-full pl-10 pr-4 py-2 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-xs font-bold text-slate-900 dark:text-slate-100 placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-primary-500"
                    />
                </div>
            </div>

            {/* Flowchart Grid List */}
            {loading ? (
                <div className="py-20 text-center text-slate-400 text-sm font-bold">
                    Loading your flowcharts...
                </div>
            ) : flowcharts.length === 0 ? (
                <div className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 p-12 text-center max-w-md mx-auto space-y-4">
                    <div className="w-16 h-16 rounded-2xl bg-slate-100 dark:bg-slate-800 text-slate-400 flex items-center justify-center mx-auto">
                        <MdAccountTree size={32} />
                    </div>
                    <div>
                        <h3 className="text-lg font-black text-slate-900 dark:text-slate-100">No Flowcharts Found</h3>
                        <p className="text-xs text-slate-500 font-medium mt-1">
                            Create a blank diagram, load a pre-built template, or auto-generate from plain text steps.
                        </p>
                    </div>
                    <button
                        onClick={() => setShowTemplatesModal(true)}
                        className="px-5 py-2.5 rounded-xl bg-primary-600 text-white font-extrabold text-xs shadow-md"
                    >
                        Browse Process Templates
                    </button>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {flowcharts.map(fc => (
                        <div
                            key={fc._id}
                            onClick={() => setActiveFlowchart(fc)}
                            className="bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 p-6 shadow-xl hover:border-primary-500 dark:hover:border-primary-500 transition-all cursor-pointer group flex flex-col justify-between"
                        >
                            <div className="space-y-3">
                                <div className="flex items-center justify-between">
                                    <span className="px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest bg-primary-50 dark:bg-primary-950/40 text-primary-600 dark:text-primary-400 border border-primary-100 dark:border-primary-900">
                                        {fc.category || 'General'}
                                    </span>
                                    <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold ${fc.status === 'Published' ? 'bg-emerald-100 text-emerald-700' : fc.status === 'Archived' ? 'bg-slate-100 text-slate-600' : 'bg-amber-100 text-amber-700'}`}>
                                        {fc.status || 'Draft'}
                                    </span>
                                </div>

                                <h3 className="text-lg font-black text-slate-900 dark:text-slate-100 group-hover:text-primary-600 transition-colors leading-tight">
                                    {fc.title}
                                </h3>
                                <p className="text-xs text-slate-500 line-clamp-2 leading-relaxed">
                                    {fc.description || 'No description provided.'}
                                </p>
                            </div>

                            <div className="pt-6 border-t border-slate-100 dark:border-slate-800/80 flex items-center justify-between mt-4">
                                <div className="flex items-center gap-3 text-xs font-bold text-slate-400">
                                    <span>{fc.nodes?.length || 0} nodes</span>
                                    <span>•</span>
                                    <span>{fc.versions?.length || 1} ver</span>
                                </div>

                                <div className="flex items-center gap-2">
                                    <button
                                        onClick={(e) => handleDeleteFlowchart(fc._id, e)}
                                        className="p-2 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-xl transition-colors"
                                        title="Delete flowchart"
                                    >
                                        <MdDelete size={18} />
                                    </button>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            )}

            {/* Create Blank Flowchart Modal */}
            <Modal
                isOpen={showNewModal}
                onClose={() => setShowNewModal(false)}
                title="Create New Flowchart"
            >
                <form onSubmit={handleCreateNew} className="space-y-4">
                    <div>
                        <label className="text-xs font-bold text-slate-700 dark:text-slate-300">Flowchart Title *</label>
                        <input
                            type="text"
                            required
                            value={formData.title}
                            onChange={(e) => setFormData({ ...formData, title: e.target.value })}
                            placeholder="e.g. Sales Order Approval Process"
                            className="w-full mt-1 p-3 rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-sm font-semibold text-slate-900 dark:text-slate-100"
                        />
                    </div>

                    <div>
                        <label className="text-xs font-bold text-slate-700 dark:text-slate-300">Category</label>
                        <input
                            type="text"
                            value={formData.category}
                            onChange={(e) => setFormData({ ...formData, category: e.target.value })}
                            placeholder="e.g. Sales, Service, HR"
                            className="w-full mt-1 p-3 rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-sm font-semibold text-slate-900 dark:text-slate-100"
                        />
                    </div>

                    <div>
                        <label className="text-xs font-bold text-slate-700 dark:text-slate-300">Description</label>
                        <textarea
                            rows={3}
                            value={formData.description}
                            onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                            placeholder="Brief summary of what this flowchart documents..."
                            className="w-full mt-1 p-3 rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-sm font-medium text-slate-900 dark:text-slate-100"
                        />
                    </div>

                    <div className="flex justify-end gap-3 pt-4 border-t border-slate-100 dark:border-slate-800">
                        <button
                            type="button"
                            onClick={() => setShowNewModal(false)}
                            className="px-5 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-300 font-bold text-xs"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            className="px-6 py-2.5 rounded-xl bg-primary-600 text-white font-extrabold text-xs shadow-md"
                        >
                            Open Canvas Editor
                        </button>
                    </div>
                </form>
            </Modal>

            {/* Auto Generator Modal */}
            <Modal
                isOpen={showAutoGenerator}
                onClose={() => setShowAutoGenerator(false)}
                title="Auto Flowchart Generator"
                maxWidth="max-w-5xl"
            >
                <AutoFlowchartGenerator
                    onGenerated={handleAutoGenerated}
                    onClose={() => setShowAutoGenerator(false)}
                />
            </Modal>

            {/* Templates Selector Modal */}
            <Modal
                isOpen={showTemplatesModal}
                onClose={() => setShowTemplatesModal(false)}
                title="Process Flowchart Templates"
                maxWidth="max-w-5xl"
            >
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 max-h-[32rem] overflow-y-auto pr-1">
                    {FLOWCHART_TEMPLATES.map(tmpl => (
                        <div
                            key={tmpl.id}
                            onClick={() => handleSelectTemplate(tmpl)}
                            className="p-5 rounded-2xl border border-slate-200 dark:border-slate-800 hover:border-primary-500 bg-slate-50/50 dark:bg-slate-800/40 hover:bg-white dark:hover:bg-slate-800 transition-all cursor-pointer flex flex-col justify-between space-y-3 group shadow-sm hover:shadow-md"
                        >
                            <div className="space-y-2">
                                <span className="px-2.5 py-0.5 rounded-full text-[10px] font-black uppercase tracking-widest bg-primary-100 text-primary-700 dark:bg-primary-900 dark:text-primary-300">
                                    {tmpl.category}
                                </span>
                                <h4 className="font-black text-slate-900 dark:text-slate-100 text-sm group-hover:text-primary-600 transition-colors">
                                    {tmpl.title}
                                </h4>
                                <p className="text-xs text-slate-500 font-medium leading-relaxed">
                                    {tmpl.description}
                                </p>
                            </div>
                            <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-[11px] font-bold text-slate-400">
                                <span>{tmpl.nodes?.length || 0} Nodes</span>
                                <span className="text-primary-600 font-black group-hover:underline">Use Template →</span>
                            </div>
                        </div>
                    ))}
                </div>
            </Modal>

            {/* Import JSON Modal */}
            <Modal
                isOpen={showImportModal}
                onClose={() => setShowImportModal(false)}
                title="Import Flowchart JSON"
            >
                <div className="space-y-4">
                    <p className="text-xs text-slate-500 font-medium">
                        Paste exported flowchart JSON content below to recreate the diagram and nodes.
                    </p>
                    <textarea
                        rows={8}
                        value={importJsonText}
                        onChange={(e) => setImportJsonText(e.target.value)}
                        placeholder={`{\n  "title": "Imported Process",\n  "nodes": [...],\n  "edges": [...]\n}`}
                        className="w-full p-3 rounded-2xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-xs font-mono text-slate-900 dark:text-slate-100"
                    />
                    <div className="flex justify-end gap-3 pt-2">
                        <button
                            type="button"
                            onClick={() => setShowImportModal(false)}
                            className="px-5 py-2.5 rounded-xl border border-slate-200 text-slate-600 font-bold text-xs"
                        >
                            Cancel
                        </button>
                        <button
                            type="button"
                            onClick={handleImportJSON}
                            className="px-6 py-2.5 rounded-xl bg-primary-600 text-white font-extrabold text-xs shadow-md"
                        >
                            Import & Open
                        </button>
                    </div>
                </div>
            </Modal>
        </div>
    );
};

export default Flowcharts;
